### ISSUE TITLE
ffprobe is creating problem

### ISSUE THREAD

**Issue by foyzulkarim** [foyzulkarim/mern-video-streaming#70]
## error
```
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "node_modules/@ffprobe-installer/darwin-arm64": name can only contain URL-friendly characters

```

<img width="1405" alt="image" src="https://github.com/foyzulkarim/mern-video-streaming/assets/497812/d7880ad9-3434-4b1b-8d5e-7a55a8fc980f">

Error log

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/foyzul/.nvm/versions/node/v14.21.3/bin/node',
1 verbose cli   '/Users/foyzul/.nvm/versions/node/v14.21.3/bin/npm',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.14.18
3 info using node@v14.21.3
4 verbose npm-session da2df17eba8b9348
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall server@1.0.0
7 info lifecycle server@1.0.0~preinstall: server@1.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 4ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:rollbackFailedOptional Completed in 0ms
16 timing stage:runTopLevelLifecycles Completed in 25ms
17 silly saveTree server@1.0.0
17 silly saveTree ├── @faker-js/faker@7.6.0
17 silly saveTree └─┬ @ffmpeg-installer/ffmpeg@1.1.0
17 silly saveTree   ├── @ffmpeg-installer/darwin-arm64@4.1.5
17 silly saveTree   ├── @ffmpeg-installer/darwin-x64@4.1.0
17 silly saveTree   ├── @ffmpeg-installer/linux-arm@4.1.3
17 silly saveTree   ├── @ffmpeg-installer/linux-arm64@4.1.4
17 silly saveTree   ├── @ffmpeg-installer/linux-ia32@4.1.0
17 silly saveTree   ├── @ffmpeg-installer/linux-x64@4.1.0
17 silly saveTree   ├── @ffmpeg-installer/win32-ia32@4.1.0
17 silly saveTree   └── @ffmpeg-installer/win32-x64@4.1.0
18 verbose stack Error: Invalid package name "node_modules/@ffprobe-installer/darwin-arm64": name can only contain URL-friendly characters
18 verbose stack     at invalidPackageName (/Users/foyzul/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:86:15)
18 verbose stack     at Result.setName (/Users/foyzul/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:121:11)
18 verbose stack     at new Result (/Users/foyzul/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:111:23)
18 verbose stack     at Function.resolve (/Users/foyzul/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:58:15)
18 verbose stack     at module.exports (/Users/foyzul/.nvm/versions/node/v14.21.3/lib/node_modules/npm/lib/install/realize-shrinkwrap-specifier.js:21:14)
18 verbose stack     at /Users/foyzul/.nvm/versions/node/v14.21.3/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:54:23
18 verbose stack     at tryCatcher (/Users/foyzul/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
18 verbose stack     at Object.gotValue (/Users/foyzul/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:166:18)
18 verbose stack     at Object.gotAccum (/Users/foyzul/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:25)
18 verbose stack     at Object.tryCatcher (/Users/foyzul/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
18 verbose stack     at Promise._settlePromiseFromHandler (/Users/foyzul/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:547:31)
18 verbose stack     at Promise._settlePromise (/Users/foyzul/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:604:18)
18 verbose stack     at Promise._settlePromise0 (/Users/foyzul/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:649:10)
18 verbose stack     at Promise._settlePromises (/Users/foyzul/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:729:18)
18 verbose stack     at _drainQueueStep (/Users/foyzul/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:93:12)
18 verbose stack     at _drainQueue (/Users/foyzul/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:86:9)
19 verbose cwd /Users/foyzul/personal/github/mern-video-streaming/server
20 verbose Darwin 22.6.0
21 verbose argv "/Users/foyzul/.nvm/versions/node/v14.21.3/bin/node" "/Users/foyzul/.nvm/versions/node/v14.21.3/bin/npm" "install"
22 verbose node v14.21.3
23 verbose npm  v6.14.18
24 error code EINVALIDPACKAGENAME
25 error Invalid package name "node_modules/@ffprobe-installer/darwin-arm64": name can only contain URL-friendly characters
26 verbose exit [ 1, true ]

```

**Comment by foyzulkarim** [comment]
@aninda052  please undo the changes quickly. we wil sort out the solution later. 
the main development is stuck

**Comment by foyzulkarim** [comment]
This answer gives an example
https://stackoverflow.com/a/59085807

**Comment by aninda052** [comment]
> This answer gives an example https://stackoverflow.com/a/59085807

@foyzulkarim vai, i checked the solution, but it's not working

**Comment by foyzulkarim** [comment]
I'll check again. No worries.

**Comment by foyzulkarim** [comment]
solved it by dockerizing the whole system. thanks 😊
